# Generated by Django 4.2 on 2023-05-22 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_productvaraiant_unique_prod_color_size_combo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvaraiant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_Varaiant_item', to='product.product'),
        ),
    ]
