# Generated by Django 4.2 on 2023-06-15 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_remove_product_color_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
