# Generated by Django 4.2 on 2023-06-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_userinformation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInformation',
        ),
    ]
