# Generated by Django 4.2 on 2023-07-11 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_delete_userinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='products_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product.product'),
            preserve_default=False,
        ),
    ]
