# Generated by Django 4.2 on 2023-05-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_order', models.CharField(choices=[(1, 'پست سفارشی تحویل یک روزه با قیمت 100000'), (2, 'پست عادی تحویل 3-7 روزه با قیمت 20000'), (3, 'پیک تحویل 5-8 روزه با قیمت 30000')], max_length=50)),
            ],
        ),
    ]
