# Generated by Django 4.2 on 2023-05-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.PositiveIntegerField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='orderchoice',
            name='choice_order',
            field=models.CharField(choices=[('پست سفارشی تحویل یک روزه با قیمت 100000', 1), ('پست عادی تحویل 3-7 روزه با قیمت 20000', 2), ('پیک تحویل 5-8 روزه با قیمت 30000', 3)], max_length=50),
        ),
    ]
